(define (problem complete-jobs) (:domain agents-in-the-city)

(:objects 
    ; initialising all trucks
    truck1 truck2 truck3 truck4 - truck 

    ; initialising all motorcycles    
    motorcycle1 motorcycle2 motorcycle3 motorcycle4 - motorcycle

    ; initialising all drones
    drone1 drone2 drone3 drone4 - drone

    ; initialising all cars
    car1 car2 car3 car4 - car

    ; initialising all items
    item0 item1 item2 item3 item4 item5 item6 item7 item8 item9 item10 - item

    ; initialising all workshops
    workshop0 workshop1 workshop2 workshop3 - workshop

    ; initialising all storages
    storage0 storage1 storage2 storage3 storage4 - storage

    ; initialising all resource nodes
    node0 node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 - resourceNode
)

(:init
    ;todo: put the initial state's facts and numeric values here

    ; resourcenodes containing item
    ;; initialising all items in resource nodes
    (item-in-resourceNode item0 node0)
    (item-in-resourceNode item2 node1)
    (item-in-resourceNode item1 node2)
    (item-in-resourceNode item4 node3)
    (item-in-resourceNode item3 node4)
    (item-in-resourceNode item1 node5)
    (item-in-resourceNode item3 node6)
    (item-in-resourceNode item1 node7)
    (item-in-resourceNode item1 node8)
    (item-in-resourceNode item2 node9)
    (item-in-resourceNode item4 node10)

    ; initial location of the agents
    (agent-at-facility truck1 storage0)
    (agent-at-facility truck2 storage1)
    (agent-at-facility truck3 storage2)
    (agent-at-facility truck4 storage3)

    (agent-at-facility motorcycle1 storage0)
    (agent-at-facility motorcycle2 storage1)
    (agent-at-facility motorcycle3 storage2)
    (agent-at-facility motorcycle4 storage3)

    (agent-at-facility car1 storage0)
    (agent-at-facility car2 storage1)
    (agent-at-facility car3 storage2)
    (agent-at-facility car4 storage3)

    (agent-at-facility drone1 storage0)
    (agent-at-facility drone2 storage1)
    (agent-at-facility drone3 storage2)
    (agent-at-facility drone4 storage3)

    (= (total-cost) 0)

    (= (distance workshop0 workshop1) 57)
    (= (distance workshop1 workshop0) 57)
    (= (distance workshop0 workshop2) 100)
    (= (distance workshop2 workshop0) 100)
    (= (distance workshop0 workshop3) 35)
    (= (distance workshop3 workshop0) 35)
    (= (distance workshop0 storage0) 34)
    (= (distance storage0 workshop0) 34)
    (= (distance workshop0 storage1) 66)
    (= (distance storage1 workshop0) 66)
    (= (distance workshop0 storage2) 16)
    (= (distance storage2 workshop0) 16)
    (= (distance workshop0 storage3) 81)
    (= (distance storage3 workshop0) 81)
    (= (distance workshop0 storage4) 40)
    (= (distance storage4 workshop0) 40)
    (= (distance workshop0 node0) 85)
    (= (distance node0 workshop0) 85)
    (= (distance workshop0 node1) 97)
    (= (distance node1 workshop0) 97)
    (= (distance workshop0 node2) 13)
    (= (distance node2 workshop0) 13)
    (= (distance workshop0 node3) 68)
    (= (distance node3 workshop0) 68)
    (= (distance workshop0 node4) 86)
    (= (distance node4 workshop0) 86)
    (= (distance workshop0 node5) 86)
    (= (distance node5 workshop0) 86)
    (= (distance workshop0 node6) 13)
    (= (distance node6 workshop0) 13)
    (= (distance workshop0 node7) 63)
    (= (distance node7 workshop0) 63)
    (= (distance workshop0 node8) 71)
    (= (distance node8 workshop0) 71)
    (= (distance workshop0 node9) 20)
    (= (distance node9 workshop0) 20)
    (= (distance workshop0 node10) 55)
    (= (distance node10 workshop0) 55)
    (= (distance workshop1 workshop2) 6)
    (= (distance workshop2 workshop1) 6)
    (= (distance workshop1 workshop3) 13)
    (= (distance workshop3 workshop1) 13)
    (= (distance workshop1 storage0) 43)
    (= (distance storage0 workshop1) 43)
    (= (distance workshop1 storage1) 30)
    (= (distance storage1 workshop1) 30)
    (= (distance workshop1 storage2) 31)
    (= (distance storage2 workshop1) 31)
    (= (distance workshop1 storage3) 27)
    (= (distance storage3 workshop1) 27)
    (= (distance workshop1 storage4) 14)
    (= (distance storage4 workshop1) 14)
    (= (distance workshop1 node0) 62)
    (= (distance node0 workshop1) 62)
    (= (distance workshop1 node1) 97)
    (= (distance node1 workshop1) 97)
    (= (distance workshop1 node2) 99)
    (= (distance node2 workshop1) 99)
    (= (distance workshop1 node3) 56)
    (= (distance node3 workshop1) 56)
    (= (distance workshop1 node4) 29)
    (= (distance node4 workshop1) 29)
    (= (distance workshop1 node5) 17)
    (= (distance node5 workshop1) 17)
    (= (distance workshop1 node6) 8)
    (= (distance node6 workshop1) 8)
    (= (distance workshop1 node7) 84)
    (= (distance node7 workshop1) 84)
    (= (distance workshop1 node8) 33)
    (= (distance node8 workshop1) 33)
    (= (distance workshop1 node9) 26)
    (= (distance node9 workshop1) 26)
    (= (distance workshop1 node10) 31)
    (= (distance node10 workshop1) 31)
    (= (distance workshop2 workshop3) 67)
    (= (distance workshop3 workshop2) 67)
    (= (distance workshop2 storage0) 35)
    (= (distance storage0 workshop2) 35)
    (= (distance workshop2 storage1) 80)
    (= (distance storage1 workshop2) 80)
    (= (distance workshop2 storage2) 24)
    (= (distance storage2 workshop2) 24)
    (= (distance workshop2 storage3) 13)
    (= (distance storage3 workshop2) 13)
    (= (distance workshop2 storage4) 31)
    (= (distance storage4 workshop2) 31)
    (= (distance workshop2 node0) 19)
    (= (distance node0 workshop2) 19)
    (= (distance workshop2 node1) 22)
    (= (distance node1 workshop2) 22)
    (= (distance workshop2 node2) 39)
    (= (distance node2 workshop2) 39)
    (= (distance workshop2 node3) 24)
    (= (distance node3 workshop2) 24)
    (= (distance workshop2 node4) 69)
    (= (distance node4 workshop2) 69)
    (= (distance workshop2 node5) 90)
    (= (distance node5 workshop2) 90)
    (= (distance workshop2 node6) 77)
    (= (distance node6 workshop2) 77)
    (= (distance workshop2 node7) 68)
    (= (distance node7 workshop2) 68)
    (= (distance workshop2 node8) 68)
    (= (distance node8 workshop2) 68)
    (= (distance workshop2 node9) 64)
    (= (distance node9 workshop2) 64)
    (= (distance workshop2 node10) 61)
    (= (distance node10 workshop2) 61)
    (= (distance workshop3 storage0) 76)
    (= (distance storage0 workshop3) 76)
    (= (distance workshop3 storage1) 1)
    (= (distance storage1 workshop3) 1)
    (= (distance workshop3 storage2) 69)
    (= (distance storage2 workshop3) 69)
    (= (distance workshop3 storage3) 66)
    (= (distance storage3 workshop3) 66)
    (= (distance workshop3 storage4) 72)
    (= (distance storage4 workshop3) 72)
    (= (distance workshop3 node0) 65)
    (= (distance node0 workshop3) 65)
    (= (distance workshop3 node1) 10)
    (= (distance node1 workshop3) 10)
    (= (distance workshop3 node2) 72)
    (= (distance node2 workshop3) 72)
    (= (distance workshop3 node3) 60)
    (= (distance node3 workshop3) 60)
    (= (distance workshop3 node4) 38)
    (= (distance node4 workshop3) 38)
    (= (distance workshop3 node5) 99)
    (= (distance node5 workshop3) 99)
    (= (distance workshop3 node6) 15)
    (= (distance node6 workshop3) 15)
    (= (distance workshop3 node7) 93)
    (= (distance node7 workshop3) 93)
    (= (distance workshop3 node8) 70)
    (= (distance node8 workshop3) 70)
    (= (distance workshop3 node9) 65)
    (= (distance node9 workshop3) 65)
    (= (distance workshop3 node10) 98)
    (= (distance node10 workshop3) 98)
    (= (distance storage0 storage1) 48)
    (= (distance storage1 storage0) 48)
    (= (distance storage0 storage2) 35)
    (= (distance storage2 storage0) 35)
    (= (distance storage0 storage3) 54)
    (= (distance storage3 storage0) 54)
    (= (distance storage0 storage4) 37)
    (= (distance storage4 storage0) 37)
    (= (distance storage0 node0) 57)
    (= (distance node0 storage0) 57)
    (= (distance storage0 node1) 42)
    (= (distance node1 storage0) 42)
    (= (distance storage0 node2) 71)
    (= (distance node2 storage0) 71)
    (= (distance storage0 node3) 96)
    (= (distance node3 storage0) 96)
    (= (distance storage0 node4) 79)
    (= (distance node4 storage0) 79)
    (= (distance storage0 node5) 91)
    (= (distance node5 storage0) 91)
    (= (distance storage0 node6) 7)
    (= (distance node6 storage0) 7)
    (= (distance storage0 node7) 95)
    (= (distance node7 storage0) 95)
    (= (distance storage0 node8) 79)
    (= (distance node8 storage0) 79)
    (= (distance storage0 node9) 16)
    (= (distance node9 storage0) 16)
    (= (distance storage0 node10) 43)
    (= (distance node10 storage0) 43)
    (= (distance storage1 storage2) 8)
    (= (distance storage2 storage1) 8)
    (= (distance storage1 storage3) 33)
    (= (distance storage3 storage1) 33)
    (= (distance storage1 storage4) 32)
    (= (distance storage4 storage1) 32)
    (= (distance storage1 node0) 77)
    (= (distance node0 storage1) 77)
    (= (distance storage1 node1) 71)
    (= (distance node1 storage1) 71)
    (= (distance storage1 node2) 77)
    (= (distance node2 storage1) 77)
    (= (distance storage1 node3) 23)
    (= (distance node3 storage1) 23)
    (= (distance storage1 node4) 52)
    (= (distance node4 storage1) 52)
    (= (distance storage1 node5) 15)
    (= (distance node5 storage1) 15)
    (= (distance storage1 node6) 87)
    (= (distance node6 storage1) 87)
    (= (distance storage1 node7) 45)
    (= (distance node7 storage1) 45)
    (= (distance storage1 node8) 44)
    (= (distance node8 storage1) 44)
    (= (distance storage1 node9) 77)
    (= (distance node9 storage1) 77)
    (= (distance storage1 node10) 96)
    (= (distance node10 storage1) 96)
    (= (distance storage2 storage3) 95)
    (= (distance storage3 storage2) 95)
    (= (distance storage2 storage4) 82)
    (= (distance storage4 storage2) 82)
    (= (distance storage2 node0) 26)
    (= (distance node0 storage2) 26)
    (= (distance storage2 node1) 7)
    (= (distance node1 storage2) 7)
    (= (distance storage2 node2) 10)
    (= (distance node2 storage2) 10)
    (= (distance storage2 node3) 33)
    (= (distance node3 storage2) 33)
    (= (distance storage2 node4) 6)
    (= (distance node4 storage2) 6)
    (= (distance storage2 node5) 4)
    (= (distance node5 storage2) 4)
    (= (distance storage2 node6) 22)
    (= (distance node6 storage2) 22)
    (= (distance storage2 node7) 47)
    (= (distance node7 storage2) 47)
    (= (distance storage2 node8) 19)
    (= (distance node8 storage2) 19)
    (= (distance storage2 node9) 37)
    (= (distance node9 storage2) 37)
    (= (distance storage2 node10) 7)
    (= (distance node10 storage2) 7)
    (= (distance storage3 storage4) 97)
    (= (distance storage4 storage3) 97)
    (= (distance storage3 node0) 97)
    (= (distance node0 storage3) 97)
    (= (distance storage3 node1) 52)
    (= (distance node1 storage3) 52)
    (= (distance storage3 node2) 74)
    (= (distance node2 storage3) 74)
    (= (distance storage3 node3) 89)
    (= (distance node3 storage3) 89)
    (= (distance storage3 node4) 86)
    (= (distance node4 storage3) 86)
    (= (distance storage3 node5) 11)
    (= (distance node5 storage3) 11)
    (= (distance storage3 node6) 56)
    (= (distance node6 storage3) 56)
    (= (distance storage3 node7) 49)
    (= (distance node7 storage3) 49)
    (= (distance storage3 node8) 17)
    (= (distance node8 storage3) 17)
    (= (distance storage3 node9) 20)
    (= (distance node9 storage3) 20)
    (= (distance storage3 node10) 62)
    (= (distance node10 storage3) 62)
    (= (distance storage4 node0) 52)
    (= (distance node0 storage4) 52)
    (= (distance storage4 node1) 87)
    (= (distance node1 storage4) 87)
    (= (distance storage4 node2) 8)
    (= (distance node2 storage4) 8)
    (= (distance storage4 node3) 55)
    (= (distance node3 storage4) 55)
    (= (distance storage4 node4) 95)
    (= (distance node4 storage4) 95)
    (= (distance storage4 node5) 49)
    (= (distance node5 storage4) 49)
    (= (distance storage4 node6) 53)
    (= (distance node6 storage4) 53)
    (= (distance storage4 node7) 69)
    (= (distance node7 storage4) 69)
    (= (distance storage4 node8) 21)
    (= (distance node8 storage4) 21)
    (= (distance storage4 node9) 4)
    (= (distance node9 storage4) 4)
    (= (distance storage4 node10) 74)
    (= (distance node10 storage4) 74)
    (= (distance node0 node1) 88)
    (= (distance node1 node0) 88)
    (= (distance node0 node2) 54)
    (= (distance node2 node0) 54)
    (= (distance node0 node3) 66)
    (= (distance node3 node0) 66)
    (= (distance node0 node4) 67)
    (= (distance node4 node0) 67)
    (= (distance node0 node5) 61)
    (= (distance node5 node0) 61)
    (= (distance node0 node6) 49)
    (= (distance node6 node0) 49)
    (= (distance node0 node7) 100)
    (= (distance node7 node0) 100)
    (= (distance node0 node8) 41)
    (= (distance node8 node0) 41)
    (= (distance node0 node9) 27)
    (= (distance node9 node0) 27)
    (= (distance node0 node10) 89)
    (= (distance node10 node0) 89)
    (= (distance node1 node2) 99)
    (= (distance node2 node1) 99)
    (= (distance node1 node3) 93)
    (= (distance node3 node1) 93)
    (= (distance node1 node4) 73)
    (= (distance node4 node1) 73)
    (= (distance node1 node5) 55)
    (= (distance node5 node1) 55)
    (= (distance node1 node6) 77)
    (= (distance node6 node1) 77)
    (= (distance node1 node7) 86)
    (= (distance node7 node1) 86)
    (= (distance node1 node8) 65)
    (= (distance node8 node1) 65)
    (= (distance node1 node9) 21)
    (= (distance node9 node1) 21)
    (= (distance node1 node10) 66)
    (= (distance node10 node1) 66)
    (= (distance node2 node3) 94)
    (= (distance node3 node2) 94)
    (= (distance node2 node4) 51)
    (= (distance node4 node2) 51)
    (= (distance node2 node5) 67)
    (= (distance node5 node2) 67)
    (= (distance node2 node6) 47)
    (= (distance node6 node2) 47)
    (= (distance node2 node7) 44)
    (= (distance node7 node2) 44)
    (= (distance node2 node8) 95)
    (= (distance node8 node2) 95)
    (= (distance node2 node9) 75)
    (= (distance node9 node2) 75)
    (= (distance node2 node10) 43)
    (= (distance node10 node2) 43)
    (= (distance node3 node4) 85)
    (= (distance node4 node3) 85)
    (= (distance node3 node5) 5)
    (= (distance node5 node3) 5)
    (= (distance node3 node6) 35)
    (= (distance node6 node3) 35)
    (= (distance node3 node7) 68)
    (= (distance node7 node3) 68)
    (= (distance node3 node8) 59)
    (= (distance node8 node3) 59)
    (= (distance node3 node9) 54)
    (= (distance node9 node3) 54)
    (= (distance node3 node10) 66)
    (= (distance node10 node3) 66)
    (= (distance node4 node5) 62)
    (= (distance node5 node4) 62)
    (= (distance node4 node6) 60)
    (= (distance node6 node4) 60)
    (= (distance node4 node7) 17)
    (= (distance node7 node4) 17)
    (= (distance node4 node8) 8)
    (= (distance node8 node4) 8)
    (= (distance node4 node9) 37)
    (= (distance node9 node4) 37)
    (= (distance node4 node10) 6)
    (= (distance node10 node4) 6)
    (= (distance node5 node6) 65)
    (= (distance node6 node5) 65)
    (= (distance node5 node7) 100)
    (= (distance node7 node5) 100)
    (= (distance node5 node8) 11)
    (= (distance node8 node5) 11)
    (= (distance node5 node9) 67)
    (= (distance node9 node5) 67)
    (= (distance node5 node10) 64)
    (= (distance node10 node5) 64)
    (= (distance node6 node7) 16)
    (= (distance node7 node6) 16)
    (= (distance node6 node8) 97)
    (= (distance node8 node6) 97)
    (= (distance node6 node9) 79)
    (= (distance node9 node6) 79)
    (= (distance node6 node10) 16)
    (= (distance node10 node6) 16)
    (= (distance node7 node8) 77)
    (= (distance node8 node7) 77)
    (= (distance node7 node9) 18)
    (= (distance node9 node7) 18)
    (= (distance node7 node10) 37)
    (= (distance node10 node7) 37)
    (= (distance node8 node9) 3)
    (= (distance node9 node8) 3)
    (= (distance node8 node10) 95)
    (= (distance node10 node8) 95)
    (= (distance node9 node10) 15)
    (= (distance node10 node9) 15)

    (= (distance workshop0 workshop0) 0)
    (= (distance workshop1 workshop1) 0)
    (= (distance workshop2 workshop2) 0)
    (= (distance workshop3 workshop3) 0)
    (= (distance storage0 storage0) 0)
    (= (distance storage1 storage1) 0)
    (= (distance storage2 storage2) 0)
    (= (distance storage3 storage3) 0)
    (= (distance storage4 storage4) 0)
    (= (distance node0 node0) 0)
    (= (distance node1 node1) 0)
    (= (distance node2 node2) 0)
    (= (distance node3 node3) 0)
    (= (distance node4 node4) 0)
    (= (distance node5 node5) 0)
    (= (distance node6 node6) 0)
    (= (distance node7 node7) 0)
    (= (distance node8 node8) 0)
    (= (distance node9 node9) 0)


)

(:goal (and
        (agent-carrying-item truck1 item9)
    )
)

;un-comment the following line if metric is needed
(:metric minimize (total-cost))
)
