(define (problem complete-jobs) (:domain agents-in-the-city)

(:objects 
    ; initialising all trucks
    truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 truck10 truck11 truck12 - truck 

    ; initialising all motorcycles    
    motorcycle1 motorcycle2 motorcycle3 motorcycle4 motorcycle5 motorcycle6 - motorcycle

    ; initialising all drones
    drone1 drone2 drone3 drone4 - drone

    ; initialising all cars
    car1 car2 car3 car4 car5 car6 car7 car8 car9 car10 - car

    ; initialising all items
    item0 item1 item2 item3 item4 item5 item6 item7 item8 item9 item10 - item

    ; initialising all workshops
    workshop0 workshop1 workshop2 workshop3 - workshop

    ; initialising all storages
    storage0 storage1 storage2 storage3 storage4 - storage

    ; initialising all resource nodes
    node0 node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 - resourceNode
)

(:init
    ;todo: put the initial state's facts and numeric values here

    ; resourcenodes containing item
    ;; initialising all items in resource nodes
    (item-in-resourceNode item0 node0)
    (item-in-resourceNode item2 node1)
    (item-in-resourceNode item1 node2)
    (item-in-resourceNode item4 node3)
    (item-in-resourceNode item3 node4)
    (item-in-resourceNode item1 node5)
    (item-in-resourceNode item3 node6)
    (item-in-resourceNode item1 node7)
    (item-in-resourceNode item1 node8)
    (item-in-resourceNode item2 node9)
    (item-in-resourceNode item4 node10)

    (= (distance workshop0 workshop1))
    (= (distance workshop0 workshop2))
    (= (distance workshop0 workshop3))

    (= (distance workshop0 storage0))
    (= (distance workshop0 storage1))
    (= (distance workshop0 storage2))
    (= (distance workshop0 storage3))
    (= (distance workshop0 storage4))

    (= (distance workshop0 node0))
    (= (distance workshop0 node1))
    (= (distance workshop0 node2))
    (= (distance workshop0 node3))
    (= (distance workshop0 node4))
    (= (distance workshop0 node5))
    (= (distance workshop0 node6))
    (= (distance workshop0 node7))
    (= (distance workshop0 node8))
    (= (distance workshop0 node9))
    (= (distance workshop0 node))
    

    ; initial location of the agents
    (agent-at-facility truck1 storage0)
    (agent-at-facility truck2 storage1)
    (agent-at-facility truck3 storage2)
    (agent-at-facility truck4 storage3)

    (agent-at-facility motorcycle1 storage0)
    (agent-at-facility motorcycle2 storage1)
    (agent-at-facility motorcycle3 storage2)
    (agent-at-facility motorcycle4 storage3)

    (agent-at-facility car1 storage0)
    (agent-at-facility car2 storage1)
    (agent-at-facility car3 storage2)
    (agent-at-facility car4 storage3)

    (agent-at-facility drone1 storage0)
    (agent-at-facility drone2 storage1)
    (agent-at-facility drone3 storage2)
    (agent-at-facility drone4 storage3)

    (= (total-cost) 0)

    (= (distance workshop0 workshop1) 31)
    (= (distance workshop0 workshop2) 1)
    (= (distance workshop0 workshop3) 33)
    (= (distance workshop0 storage0) 16)
    (= (distance workshop0 storage1) 50)
    (= (distance workshop0 storage2) 32)
    (= (distance workshop0 storage3) 40)
    (= (distance workshop0 storage4) 9)
    (= (distance workshop0 node0) 43)
    (= (distance workshop0 node1) 45)
    (= (distance workshop0 node2) 17)
    (= (distance workshop0 node3) 44)
    (= (distance workshop0 node4) 39)
    (= (distance workshop0 node5) 14)
    (= (distance workshop0 node6) 45)
    (= (distance workshop0 node7) 29)
    (= (distance workshop0 node8) 1)
    (= (distance workshop0 node9) 40)
    (= (distance workshop0 node10) 37)
    (= (distance workshop1 workshop0) 5)
    (= (distance workshop1 workshop2) 11)
    (= (distance workshop1 workshop3) 29)
    (= (distance workshop1 storage0) 13)
    (= (distance workshop1 storage1) 47)
    (= (distance workshop1 storage2) 44)
    (= (distance workshop1 storage3) 4)
    (= (distance workshop1 storage4) 34)
    (= (distance workshop1 node0) 41)
    (= (distance workshop1 node1) 46)
    (= (distance workshop1 node2) 12)
    (= (distance workshop1 node3) 20)
    (= (distance workshop1 node4) 34)
    (= (distance workshop1 node5) 28)
    (= (distance workshop1 node6) 20)
    (= (distance workshop1 node7) 39)
    (= (distance workshop1 node8) 44)
    (= (distance workshop1 node9) 44)
    (= (distance workshop1 node10) 37)
    (= (distance workshop2 workshop0) 49)
    (= (distance workshop2 workshop1) 13)
    (= (distance workshop2 workshop3) 26)
    (= (distance workshop2 storage0) 17)
    (= (distance workshop2 storage1) 17)
    (= (distance workshop2 storage2) 35)
    (= (distance workshop2 storage3) 28)
    (= (distance workshop2 storage4) 16)
    (= (distance workshop2 node0) 7)
    (= (distance workshop2 node1) 31)
    (= (distance workshop2 node2) 8)
    (= (distance workshop2 node3) 34)
    (= (distance workshop2 node4) 17)
    (= (distance workshop2 node5) 9)
    (= (distance workshop2 node6) 13)
    (= (distance workshop2 node7) 41)
    (= (distance workshop2 node8) 21)
    (= (distance workshop2 node9) 1)
    (= (distance workshop2 node10) 3)
    (= (distance workshop3 workshop0) 38)
    (= (distance workshop3 workshop1) 15)
    (= (distance workshop3 workshop2) 9)
    (= (distance workshop3 storage0) 15)
    (= (distance workshop3 storage1) 17)
    (= (distance workshop3 storage2) 45)
    (= (distance workshop3 storage3) 16)
    (= (distance workshop3 storage4) 24)
    (= (distance workshop3 node0) 50)
    (= (distance workshop3 node1) 9)
    (= (distance workshop3 node2) 48)
    (= (distance workshop3 node3) 42)
    (= (distance workshop3 node4) 29)
    (= (distance workshop3 node5) 18)
    (= (distance workshop3 node6) 10)
    (= (distance workshop3 node7) 34)
    (= (distance workshop3 node8) 25)
    (= (distance workshop3 node9) 30)
    (= (distance workshop3 node10) 1)
    (= (distance storage0 workshop0) 17)
    (= (distance storage0 workshop1) 22)
    (= (distance storage0 workshop2) 16)
    (= (distance storage0 workshop3) 27)
    (= (distance storage0 storage1) 13)
    (= (distance storage0 storage2) 23)
    (= (distance storage0 storage3) 49)
    (= (distance storage0 storage4) 18)
    (= (distance storage0 node0) 35)
    (= (distance storage0 node1) 47)
    (= (distance storage0 node2) 24)
    (= (distance storage0 node3) 1)
    (= (distance storage0 node4) 8)
    (= (distance storage0 node5) 25)
    (= (distance storage0 node6) 14)
    (= (distance storage0 node7) 47)
    (= (distance storage0 node8) 22)
    (= (distance storage0 node9) 10)
    (= (distance storage0 node10) 10)
    (= (distance storage1 workshop0) 3)
    (= (distance storage1 workshop1) 34)
    (= (distance storage1 workshop2) 23)
    (= (distance storage1 workshop3) 44)
    (= (distance storage1 storage0) 45)
    (= (distance storage1 storage2) 15)
    (= (distance storage1 storage3) 13)
    (= (distance storage1 storage4) 12)
    (= (distance storage1 node0) 29)
    (= (distance storage1 node1) 24)
    (= (distance storage1 node2) 43)
    (= (distance storage1 node3) 15)
    (= (distance storage1 node4) 3)
    (= (distance storage1 node5) 21)
    (= (distance storage1 node6) 33)
    (= (distance storage1 node7) 2)
    (= (distance storage1 node8) 50)
    (= (distance storage1 node9) 12)
    (= (distance storage1 node10) 47)
    (= (distance storage2 workshop0) 36)
    (= (distance storage2 workshop1) 3)
    (= (distance storage2 workshop2) 26)
    (= (distance storage2 workshop3) 35)
    (= (distance storage2 storage0) 14)
    (= (distance storage2 storage1) 39)
    (= (distance storage2 storage3) 40)
    (= (distance storage2 storage4) 49)
    (= (distance storage2 node0) 1)
    (= (distance storage2 node1) 41)
    (= (distance storage2 node2) 19)
    (= (distance storage2 node3) 21)
    (= (distance storage2 node4) 35)
    (= (distance storage2 node5) 42)
    (= (distance storage2 node6) 10)
    (= (distance storage2 node7) 44)
    (= (distance storage2 node8) 30)
    (= (distance storage2 node9) 2)
    (= (distance storage2 node10) 17)
    (= (distance storage3 workshop0) 25)
    (= (distance storage3 workshop1) 48)
    (= (distance storage3 workshop2) 8)
    (= (distance storage3 workshop3) 23)
    (= (distance storage3 storage0) 32)
    (= (distance storage3 storage1) 2)
    (= (distance storage3 storage2) 11)
    (= (distance storage3 storage4) 5)
    (= (distance storage3 node0) 49)
    (= (distance storage3 node1) 46)
    (= (distance storage3 node2) 23)
    (= (distance storage3 node3) 14)
    (= (distance storage3 node4) 5)
    (= (distance storage3 node5) 36)
    (= (distance storage3 node6) 32)
    (= (distance storage3 node7) 26)
    (= (distance storage3 node8) 46)
    (= (distance storage3 node9) 24)
    (= (distance storage3 node10) 38)
    (= (distance storage4 workshop0) 43)
    (= (distance storage4 workshop1) 27)
    (= (distance storage4 workshop2) 39)
    (= (distance storage4 workshop3) 3)
    (= (distance storage4 storage0) 1)
    (= (distance storage4 storage1) 33)
    (= (distance storage4 storage2) 4)
    (= (distance storage4 storage3) 32)
    (= (distance storage4 node0) 13)
    (= (distance storage4 node1) 28)
    (= (distance storage4 node2) 42)
    (= (distance storage4 node3) 10)
    (= (distance storage4 node4) 10)
    (= (distance storage4 node5) 6)
    (= (distance storage4 node6) 38)
    (= (distance storage4 node7) 37)
    (= (distance storage4 node8) 26)
    (= (distance storage4 node9) 31)
    (= (distance storage4 node10) 15)
    (= (distance node0 workshop0) 2)
    (= (distance node0 workshop1) 4)
    (= (distance node0 workshop2) 30)
    (= (distance node0 workshop3) 44)
    (= (distance node0 storage0) 44)
    (= (distance node0 storage1) 8)
    (= (distance node0 storage2) 26)
    (= (distance node0 storage3) 31)
    (= (distance node0 storage4) 41)
    (= (distance node0 node1) 30)
    (= (distance node0 node2) 22)
    (= (distance node0 node3) 36)
    (= (distance node0 node4) 39)
    (= (distance node0 node5) 9)
    (= (distance node0 node6) 7)
    (= (distance node0 node7) 23)
    (= (distance node0 node8) 39)
    (= (distance node0 node9) 47)
    (= (distance node0 node10) 12)
    (= (distance node1 workshop0) 11)
    (= (distance node1 workshop1) 27)
    (= (distance node1 workshop2) 38)
    (= (distance node1 workshop3) 42)
    (= (distance node1 storage0) 1)
    (= (distance node1 storage1) 43)
    (= (distance node1 storage2) 38)
    (= (distance node1 storage3) 5)
    (= (distance node1 storage4) 47)
    (= (distance node1 node0) 16)
    (= (distance node1 node2) 28)
    (= (distance node1 node3) 24)
    (= (distance node1 node4) 40)
    (= (distance node1 node5) 12)
    (= (distance node1 node6) 18)
    (= (distance node1 node7) 41)
    (= (distance node1 node8) 37)
    (= (distance node1 node9) 2)
    (= (distance node1 node10) 48)
    (= (distance node2 workshop0) 45)
    (= (distance node2 workshop1) 34)
    (= (distance node2 workshop2) 36)
    (= (distance node2 workshop3) 2)
    (= (distance node2 storage0) 31)
    (= (distance node2 storage1) 16)
    (= (distance node2 storage2) 44)
    (= (distance node2 storage3) 30)
    (= (distance node2 storage4) 5)
    (= (distance node2 node0) 25)
    (= (distance node2 node1) 49)
    (= (distance node2 node3) 34)
    (= (distance node2 node4) 19)
    (= (distance node2 node5) 23)
    (= (distance node2 node6) 3)
    (= (distance node2 node7) 1)
    (= (distance node2 node8) 39)
    (= (distance node2 node9) 9)
    (= (distance node2 node10) 3)
    (= (distance node3 workshop0) 19)
    (= (distance node3 workshop1) 2)
    (= (distance node3 workshop2) 5)
    (= (distance node3 workshop3) 22)
    (= (distance node3 storage0) 37)
    (= (distance node3 storage1) 30)
    (= (distance node3 storage2) 2)
    (= (distance node3 storage3) 45)
    (= (distance node3 storage4) 15)
    (= (distance node3 node0) 23)
    (= (distance node3 node1) 38)
    (= (distance node3 node2) 16)
    (= (distance node3 node4) 37)
    (= (distance node3 node5) 43)
    (= (distance node3 node6) 23)
    (= (distance node3 node7) 28)
    (= (distance node3 node8) 25)
    (= (distance node3 node9) 47)
    (= (distance node3 node10) 1)
    (= (distance node4 workshop0) 4)
    (= (distance node4 workshop1) 15)
    (= (distance node4 workshop2) 40)
    (= (distance node4 workshop3) 1)
    (= (distance node4 storage0) 13)
    (= (distance node4 storage1) 16)
    (= (distance node4 storage2) 6)
    (= (distance node4 storage3) 49)
    (= (distance node4 storage4) 43)
    (= (distance node4 node0) 25)
    (= (distance node4 node1) 17)
    (= (distance node4 node2) 1)
    (= (distance node4 node3) 22)
    (= (distance node4 node5) 12)
    (= (distance node4 node6) 5)
    (= (distance node4 node7) 33)
    (= (distance node4 node8) 28)
    (= (distance node4 node9) 41)
    (= (distance node4 node10) 20)
    (= (distance node5 workshop0) 38)
    (= (distance node5 workshop1) 28)
    (= (distance node5 workshop2) 9)
    (= (distance node5 workshop3) 17)
    (= (distance node5 storage0) 10)
    (= (distance node5 storage1) 45)
    (= (distance node5 storage2) 8)
    (= (distance node5 storage3) 29)
    (= (distance node5 storage4) 22)
    (= (distance node5 node0) 9)
    (= (distance node5 node1) 40)
    (= (distance node5 node2) 33)
    (= (distance node5 node3) 36)
    (= (distance node5 node4) 18)
    (= (distance node5 node6) 38)
    (= (distance node5 node7) 22)
    (= (distance node5 node8) 47)
    (= (distance node5 node9) 18)
    (= (distance node5 node10) 19)
    (= (distance node6 workshop0) 23)
    (= (distance node6 workshop1) 31)
    (= (distance node6 workshop2) 34)
    (= (distance node6 workshop3) 4)
    (= (distance node6 storage0) 40)
    (= (distance node6 storage1) 32)
    (= (distance node6 storage2) 45)
    (= (distance node6 storage3) 9)
    (= (distance node6 storage4) 29)
    (= (distance node6 node0) 13)
    (= (distance node6 node1) 10)
    (= (distance node6 node2) 9)
    (= (distance node6 node3) 49)
    (= (distance node6 node4) 4)
    (= (distance node6 node5) 27)
    (= (distance node6 node7) 11)
    (= (distance node6 node8) 30)
    (= (distance node6 node9) 11)
    (= (distance node6 node10) 44)
    (= (distance node7 workshop0) 20)
    (= (distance node7 workshop1) 12)
    (= (distance node7 workshop2) 3)
    (= (distance node7 workshop3) 16)
    (= (distance node7 storage0) 31)
    (= (distance node7 storage1) 7)
    (= (distance node7 storage2) 13)
    (= (distance node7 storage3) 23)
    (= (distance node7 storage4) 47)
    (= (distance node7 node0) 47)
    (= (distance node7 node1) 37)
    (= (distance node7 node2) 23)
    (= (distance node7 node3) 23)
    (= (distance node7 node4) 18)
    (= (distance node7 node5) 5)
    (= (distance node7 node6) 6)
    (= (distance node7 node8) 35)
    (= (distance node7 node9) 35)
    (= (distance node7 node10) 10)
    (= (distance node8 workshop0) 41)
    (= (distance node8 workshop1) 35)
    (= (distance node8 workshop2) 22)
    (= (distance node8 workshop3) 36)
    (= (distance node8 storage0) 40)
    (= (distance node8 storage1) 40)
    (= (distance node8 storage2) 22)
    (= (distance node8 storage3) 34)
    (= (distance node8 storage4) 35)
    (= (distance node8 node0) 8)
    (= (distance node8 node1) 22)
    (= (distance node8 node2) 13)
    (= (distance node8 node3) 9)
    (= (distance node8 node4) 16)
    (= (distance node8 node5) 34)
    (= (distance node8 node6) 1)
    (= (distance node8 node7) 7)
    (= (distance node8 node9) 18)
    (= (distance node8 node10) 4)
    (= (distance node9 workshop0) 47)
    (= (distance node9 workshop1) 36)
    (= (distance node9 workshop2) 43)
    (= (distance node9 workshop3) 47)
    (= (distance node9 storage0) 34)
    (= (distance node9 storage1) 38)
    (= (distance node9 storage2) 25)
    (= (distance node9 storage3) 50)
    (= (distance node9 storage4) 26)
    (= (distance node9 node0) 31)
    (= (distance node9 node1) 25)
    (= (distance node9 node2) 16)
    (= (distance node9 node3) 23)
    (= (distance node9 node4) 43)
    (= (distance node9 node5) 25)
    (= (distance node9 node6) 45)
    (= (distance node9 node7) 19)
    (= (distance node9 node8) 10)
    (= (distance node9 node10) 25)
    (= (distance node10 workshop0) 27)
    (= (distance node10 workshop1) 8)
    (= (distance node10 workshop2) 5)
    (= (distance node10 workshop3) 22)
    (= (distance node10 storage0) 3)
    (= (distance node10 storage1) 47)
    (= (distance node10 storage2) 27)
    (= (distance node10 storage3) 12)
    (= (distance node10 storage4) 11)
    (= (distance node10 node0) 12)
    (= (distance node10 node1) 21)
    (= (distance node10 node2) 33)
    (= (distance node10 node3) 37)
    (= (distance node10 node4) 15)
    (= (distance node10 node5) 39)
    (= (distance node10 node6) 33)
    (= (distance node10 node7) 39)
    (= (distance node10 node8) 45)
    (= (distance node10 node9) 40)
)

(:goal (and
        (agent-carrying-item truck1 item9)
    )
)

;un-comment the following line if metric is needed
(:metric minimize (total-cost))
)
