(define (problem complete-jobs) (:domain agents-in-the-city)

(:objects 
    ; initialising all trucks
    truck1 truck2 truck3 truck4 - truck 

    ; initialising all motorcycles    
    motorcycle1 motorcycle2 motorcycle3 motorcycle4 - motorcycle

    ; initialising all drones
    drone1 drone2 drone3 drone4 - drone

    ; initialising all cars
    car1 car2 car3 car4 - car

    ; initialising all items
    item0 item1 item2 item3 item4 item5 item6 item7 item8 item9 item10 - item

    ; initialising all workshops
    workshop0 workshop1 workshop2 workshop3 - workshop

    ; initialising all storages
    storage0 storage1 storage2 storage3 storage4 - storage

    ; initialising all resource nodes
    node0 node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 - resourceNode
)

(:init
    ;todo: put the initial state's facts and numeric values here

    ; resourcenodes containing item
    ;; initialising all items in resource nodes
    (item-in-resourceNode item0 node0)
    (item-in-resourceNode item2 node1)
    (item-in-resourceNode item1 node2)
    (item-in-resourceNode item4 node3)
    (item-in-resourceNode item3 node4)
    (item-in-resourceNode item1 node5)
    (item-in-resourceNode item3 node6)
    (item-in-resourceNode item1 node7)
    (item-in-resourceNode item1 node8)
    (item-in-resourceNode item2 node9)
    (item-in-resourceNode item4 node10)

    ; initial location of the agents
    (agent-at-facility truck1 storage0)
    (agent-at-facility truck2 storage1)
    (agent-at-facility truck3 storage2)
    (agent-at-facility truck4 storage3)


    (agent-at-facility motorcycle1 storage0)
    (agent-at-facility motorcycle2 storage1)
    (agent-at-facility motorcycle3 storage2)
    (agent-at-facility motorcycle4 storage3)

    (agent-at-facility car1 storage0)
    (agent-at-facility car2 storage1)
    (agent-at-facility car3 storage2)
    (agent-at-facility car4 storage3)

    (agent-at-facility drone1 storage0)
    (agent-at-facility drone2 storage1)
    (agent-at-facility drone3 storage2)
    (agent-at-facility drone4 storage3)

    (= (agent-carrying-item truck1 item0) 0)
    (= (agent-carrying-item truck1 item1) 0)
    (= (agent-carrying-item truck1 item2) 0)
    (= (agent-carrying-item truck1 item3) 0)
    (= (agent-carrying-item truck1 item4) 0)
    (= (agent-carrying-item truck1 item5) 0)
    (= (agent-carrying-item truck1 item6) 0)
    (= (agent-carrying-item truck1 item7) 0)
    (= (agent-carrying-item truck1 item8) 0)
    (= (agent-carrying-item truck1 item9) 0)
    (= (agent-carrying-item truck1 item10) 0)
    (= (agent-carrying-item truck2 item0) 0)
    (= (agent-carrying-item truck2 item1) 0)
    (= (agent-carrying-item truck2 item2) 0)
    (= (agent-carrying-item truck2 item3) 0)
    (= (agent-carrying-item truck2 item4) 0)
    (= (agent-carrying-item truck2 item5) 0)
    (= (agent-carrying-item truck2 item6) 0)
    (= (agent-carrying-item truck2 item7) 0)
    (= (agent-carrying-item truck2 item8) 0)
    (= (agent-carrying-item truck2 item9) 0)
    (= (agent-carrying-item truck2 item10) 0)
    (= (agent-carrying-item truck3 item0) 0)
    (= (agent-carrying-item truck3 item1) 0)
    (= (agent-carrying-item truck3 item2) 0)
    (= (agent-carrying-item truck3 item3) 0)
    (= (agent-carrying-item truck3 item4) 0)
    (= (agent-carrying-item truck3 item5) 0)
    (= (agent-carrying-item truck3 item6) 0)
    (= (agent-carrying-item truck3 item7) 0)
    (= (agent-carrying-item truck3 item8) 0)
    (= (agent-carrying-item truck3 item9) 0)
    (= (agent-carrying-item truck3 item10) 0)
    (= (agent-carrying-item truck4 item0) 0)
    (= (agent-carrying-item truck4 item1) 0)
    (= (agent-carrying-item truck4 item2) 0)
    (= (agent-carrying-item truck4 item3) 0)
    (= (agent-carrying-item truck4 item4) 0)
    (= (agent-carrying-item truck4 item5) 0)
    (= (agent-carrying-item truck4 item6) 0)
    (= (agent-carrying-item truck4 item7) 0)
    (= (agent-carrying-item truck4 item8) 0)
    (= (agent-carrying-item truck4 item9) 0)
    (= (agent-carrying-item truck4 item10) 0)
    (= (agent-carrying-item motorcycle1 item0) 0)
    (= (agent-carrying-item motorcycle1 item1) 0)
    (= (agent-carrying-item motorcycle1 item2) 0)
    (= (agent-carrying-item motorcycle1 item3) 0)
    (= (agent-carrying-item motorcycle1 item4) 0)
    (= (agent-carrying-item motorcycle1 item5) 0)
    (= (agent-carrying-item motorcycle1 item6) 0)
    (= (agent-carrying-item motorcycle1 item7) 0)
    (= (agent-carrying-item motorcycle1 item8) 0)
    (= (agent-carrying-item motorcycle1 item9) 0)
    (= (agent-carrying-item motorcycle1 item10) 0)
    (= (agent-carrying-item motorcycle2 item0) 0)
    (= (agent-carrying-item motorcycle2 item1) 0)
    (= (agent-carrying-item motorcycle2 item2) 0)
    (= (agent-carrying-item motorcycle2 item3) 0)
    (= (agent-carrying-item motorcycle2 item4) 0)
    (= (agent-carrying-item motorcycle2 item5) 0)
    (= (agent-carrying-item motorcycle2 item6) 0)
    (= (agent-carrying-item motorcycle2 item7) 0)
    (= (agent-carrying-item motorcycle2 item8) 0)
    (= (agent-carrying-item motorcycle2 item9) 0)
    (= (agent-carrying-item motorcycle2 item10) 0)
    (= (agent-carrying-item motorcycle3 item0) 0)
    (= (agent-carrying-item motorcycle3 item1) 0)
    (= (agent-carrying-item motorcycle3 item2) 0)
    (= (agent-carrying-item motorcycle3 item3) 0)
    (= (agent-carrying-item motorcycle3 item4) 0)
    (= (agent-carrying-item motorcycle3 item5) 0)
    (= (agent-carrying-item motorcycle3 item6) 0)
    (= (agent-carrying-item motorcycle3 item7) 0)
    (= (agent-carrying-item motorcycle3 item8) 0)
    (= (agent-carrying-item motorcycle3 item9) 0)
    (= (agent-carrying-item motorcycle3 item10) 0)
    (= (agent-carrying-item motorcycle4 item0) 0)
    (= (agent-carrying-item motorcycle4 item1) 0)
    (= (agent-carrying-item motorcycle4 item2) 0)
    (= (agent-carrying-item motorcycle4 item3) 0)
    (= (agent-carrying-item motorcycle4 item4) 0)
    (= (agent-carrying-item motorcycle4 item5) 0)
    (= (agent-carrying-item motorcycle4 item6) 0)
    (= (agent-carrying-item motorcycle4 item7) 0)
    (= (agent-carrying-item motorcycle4 item8) 0)
    (= (agent-carrying-item motorcycle4 item9) 0)
    (= (agent-carrying-item motorcycle4 item10) 0)
    (= (agent-carrying-item drone1 item0) 0)
    (= (agent-carrying-item drone1 item1) 0)
    (= (agent-carrying-item drone1 item2) 0)
    (= (agent-carrying-item drone1 item3) 0)
    (= (agent-carrying-item drone1 item4) 0)
    (= (agent-carrying-item drone1 item5) 0)
    (= (agent-carrying-item drone1 item6) 0)
    (= (agent-carrying-item drone1 item7) 0)
    (= (agent-carrying-item drone1 item8) 0)
    (= (agent-carrying-item drone1 item9) 0)
    (= (agent-carrying-item drone1 item10) 0)
    (= (agent-carrying-item drone2 item0) 0)
    (= (agent-carrying-item drone2 item1) 0)
    (= (agent-carrying-item drone2 item2) 0)
    (= (agent-carrying-item drone2 item3) 0)
    (= (agent-carrying-item drone2 item4) 0)
    (= (agent-carrying-item drone2 item5) 0)
    (= (agent-carrying-item drone2 item6) 0)
    (= (agent-carrying-item drone2 item7) 0)
    (= (agent-carrying-item drone2 item8) 0)
    (= (agent-carrying-item drone2 item9) 0)
    (= (agent-carrying-item drone2 item10) 0)
    (= (agent-carrying-item drone3 item0) 0)
    (= (agent-carrying-item drone3 item1) 0)
    (= (agent-carrying-item drone3 item2) 0)
    (= (agent-carrying-item drone3 item3) 0)
    (= (agent-carrying-item drone3 item4) 0)
    (= (agent-carrying-item drone3 item5) 0)
    (= (agent-carrying-item drone3 item6) 0)
    (= (agent-carrying-item drone3 item7) 0)
    (= (agent-carrying-item drone3 item8) 0)
    (= (agent-carrying-item drone3 item9) 0)
    (= (agent-carrying-item drone3 item10) 0)
    (= (agent-carrying-item drone4 item0) 0)
    (= (agent-carrying-item drone4 item1) 0)
    (= (agent-carrying-item drone4 item2) 0)
    (= (agent-carrying-item drone4 item3) 0)
    (= (agent-carrying-item drone4 item4) 0)
    (= (agent-carrying-item drone4 item5) 0)
    (= (agent-carrying-item drone4 item6) 0)
    (= (agent-carrying-item drone4 item7) 0)
    (= (agent-carrying-item drone4 item8) 0)
    (= (agent-carrying-item drone4 item9) 0)
    (= (agent-carrying-item drone4 item10) 0)
    (= (agent-carrying-item car1 item0) 0)
    (= (agent-carrying-item car1 item1) 0)
    (= (agent-carrying-item car1 item2) 0)
    (= (agent-carrying-item car1 item3) 0)
    (= (agent-carrying-item car1 item4) 0)
    (= (agent-carrying-item car1 item5) 0)
    (= (agent-carrying-item car1 item6) 0)
    (= (agent-carrying-item car1 item7) 0)
    (= (agent-carrying-item car1 item8) 0)
    (= (agent-carrying-item car1 item9) 0)
    (= (agent-carrying-item car1 item10) 0)
    (= (agent-carrying-item car2 item0) 0)
    (= (agent-carrying-item car2 item1) 0)
    (= (agent-carrying-item car2 item2) 0)
    (= (agent-carrying-item car2 item3) 0)
    (= (agent-carrying-item car2 item4) 0)
    (= (agent-carrying-item car2 item5) 0)
    (= (agent-carrying-item car2 item6) 0)
    (= (agent-carrying-item car2 item7) 0)
    (= (agent-carrying-item car2 item8) 0)
    (= (agent-carrying-item car2 item9) 0)
    (= (agent-carrying-item car2 item10) 0)
    (= (agent-carrying-item car3 item0) 0)
    (= (agent-carrying-item car3 item1) 0)
    (= (agent-carrying-item car3 item2) 0)
    (= (agent-carrying-item car3 item3) 0)
    (= (agent-carrying-item car3 item4) 0)
    (= (agent-carrying-item car3 item5) 0)
    (= (agent-carrying-item car3 item6) 0)
    (= (agent-carrying-item car3 item7) 0)
    (= (agent-carrying-item car3 item8) 0)
    (= (agent-carrying-item car3 item9) 0)
    (= (agent-carrying-item car3 item10) 0)
    (= (agent-carrying-item truck1 item0) 0)
    (= (agent-carrying-item truck1 item1) 0)
    (= (agent-carrying-item truck1 item2) 0)
    (= (agent-carrying-item truck1 item3) 0)
    (= (agent-carrying-item truck1 item4) 0)
    (= (agent-carrying-item truck1 item5) 0)
    (= (agent-carrying-item truck1 item6) 0)
    (= (agent-carrying-item truck1 item7) 0)
    (= (agent-carrying-item truck1 item8) 0)
    (= (agent-carrying-item truck1 item9) 0)
    (= (agent-carrying-item truck1 item10) 0)
    (= (agent-carrying-item truck2 item0) 0)
    (= (agent-carrying-item truck2 item1) 0)
    (= (agent-carrying-item truck2 item2) 0)
    (= (agent-carrying-item truck2 item3) 0)
    (= (agent-carrying-item truck2 item4) 0)
    (= (agent-carrying-item truck2 item5) 0)
    (= (agent-carrying-item truck2 item6) 0)
    (= (agent-carrying-item truck2 item7) 0)
    (= (agent-carrying-item truck2 item8) 0)
    (= (agent-carrying-item truck2 item9) 0)
    (= (agent-carrying-item truck2 item10) 0)
    (= (agent-carrying-item truck3 item0) 0)
    (= (agent-carrying-item truck3 item1) 0)
    (= (agent-carrying-item truck3 item2) 0)
    (= (agent-carrying-item truck3 item3) 0)
    (= (agent-carrying-item truck3 item4) 0)
    (= (agent-carrying-item truck3 item5) 0)
    (= (agent-carrying-item truck3 item6) 0)
    (= (agent-carrying-item truck3 item7) 0)
    (= (agent-carrying-item truck3 item8) 0)
    (= (agent-carrying-item truck3 item9) 0)
    (= (agent-carrying-item truck3 item10) 0)
    (= (agent-carrying-item truck4 item0) 0)
    (= (agent-carrying-item truck4 item1) 0)
    (= (agent-carrying-item truck4 item2) 0)
    (= (agent-carrying-item truck4 item3) 0)
    (= (agent-carrying-item truck4 item4) 0)
    (= (agent-carrying-item truck4 item5) 0)
    (= (agent-carrying-item truck4 item6) 0)
    (= (agent-carrying-item truck4 item7) 0)
    (= (agent-carrying-item truck4 item8) 0)
    (= (agent-carrying-item truck4 item9) 0)
    (= (agent-carrying-item truck4 item10) 0)
    (= (agent-carrying-item motorcycle1 item0) 0)
    (= (agent-carrying-item motorcycle1 item1) 0)
    (= (agent-carrying-item motorcycle1 item2) 0)
    (= (agent-carrying-item motorcycle1 item3) 0)
    (= (agent-carrying-item motorcycle1 item4) 0)
    (= (agent-carrying-item motorcycle1 item5) 0)
    (= (agent-carrying-item motorcycle1 item6) 0)
    (= (agent-carrying-item motorcycle1 item7) 0)
    (= (agent-carrying-item motorcycle1 item8) 0)
    (= (agent-carrying-item motorcycle1 item9) 0)
    (= (agent-carrying-item motorcycle1 item10) 0)
    (= (agent-carrying-item motorcycle2 item0) 0)
    (= (agent-carrying-item motorcycle2 item1) 0)
    (= (agent-carrying-item motorcycle2 item2) 0)
    (= (agent-carrying-item motorcycle2 item3) 0)
    (= (agent-carrying-item motorcycle2 item4) 0)
    (= (agent-carrying-item motorcycle2 item5) 0)
    (= (agent-carrying-item motorcycle2 item6) 0)
    (= (agent-carrying-item motorcycle2 item7) 0)
    (= (agent-carrying-item motorcycle2 item8) 0)
    (= (agent-carrying-item motorcycle2 item9) 0)
    (= (agent-carrying-item motorcycle2 item10) 0)
    (= (agent-carrying-item motorcycle3 item0) 0)
    (= (agent-carrying-item motorcycle3 item1) 0)
    (= (agent-carrying-item motorcycle3 item2) 0)
    (= (agent-carrying-item motorcycle3 item3) 0)
    (= (agent-carrying-item motorcycle3 item4) 0)
    (= (agent-carrying-item motorcycle3 item5) 0)
    (= (agent-carrying-item motorcycle3 item6) 0)
    (= (agent-carrying-item motorcycle3 item7) 0)
    (= (agent-carrying-item motorcycle3 item8) 0)
    (= (agent-carrying-item motorcycle3 item9) 0)
    (= (agent-carrying-item motorcycle3 item10) 0)
    (= (agent-carrying-item motorcycle4 item0) 0)
    (= (agent-carrying-item motorcycle4 item1) 0)
    (= (agent-carrying-item motorcycle4 item2) 0)
    (= (agent-carrying-item motorcycle4 item3) 0)
    (= (agent-carrying-item motorcycle4 item4) 0)
    (= (agent-carrying-item motorcycle4 item5) 0)
    (= (agent-carrying-item motorcycle4 item6) 0)
    (= (agent-carrying-item motorcycle4 item7) 0)
    (= (agent-carrying-item motorcycle4 item8) 0)
    (= (agent-carrying-item motorcycle4 item9) 0)
    (= (agent-carrying-item motorcycle4 item10) 0)
    (= (agent-carrying-item drone1 item0) 0)
    (= (agent-carrying-item drone1 item1) 0)
    (= (agent-carrying-item drone1 item2) 0)
    (= (agent-carrying-item drone1 item3) 0)
    (= (agent-carrying-item drone1 item4) 0)
    (= (agent-carrying-item drone1 item5) 0)
    (= (agent-carrying-item drone1 item6) 0)
    (= (agent-carrying-item drone1 item7) 0)
    (= (agent-carrying-item drone1 item8) 0)
    (= (agent-carrying-item drone1 item9) 0)
    (= (agent-carrying-item drone1 item10) 0)
    (= (agent-carrying-item drone2 item0) 0)
    (= (agent-carrying-item drone2 item1) 0)
    (= (agent-carrying-item drone2 item2) 0)
    (= (agent-carrying-item drone2 item3) 0)
    (= (agent-carrying-item drone2 item4) 0)
    (= (agent-carrying-item drone2 item5) 0)
    (= (agent-carrying-item drone2 item6) 0)
    (= (agent-carrying-item drone2 item7) 0)
    (= (agent-carrying-item drone2 item8) 0)
    (= (agent-carrying-item drone2 item9) 0)
    (= (agent-carrying-item drone2 item10) 0)
    (= (agent-carrying-item drone3 item0) 0)
    (= (agent-carrying-item drone3 item1) 0)
    (= (agent-carrying-item drone3 item2) 0)
    (= (agent-carrying-item drone3 item3) 0)
    (= (agent-carrying-item drone3 item4) 0)
    (= (agent-carrying-item drone3 item5) 0)
    (= (agent-carrying-item drone3 item6) 0)
    (= (agent-carrying-item drone3 item7) 0)
    (= (agent-carrying-item drone3 item8) 0)
    (= (agent-carrying-item drone3 item9) 0)
    (= (agent-carrying-item drone3 item10) 0)
    (= (agent-carrying-item drone4 item0) 0)
    (= (agent-carrying-item drone4 item1) 0)
    (= (agent-carrying-item drone4 item2) 0)
    (= (agent-carrying-item drone4 item3) 0)
    (= (agent-carrying-item drone4 item4) 0)
    (= (agent-carrying-item drone4 item5) 0)
    (= (agent-carrying-item drone4 item6) 0)
    (= (agent-carrying-item drone4 item7) 0)
    (= (agent-carrying-item drone4 item8) 0)
    (= (agent-carrying-item drone4 item9) 0)
    (= (agent-carrying-item drone4 item10) 0)
    (= (agent-carrying-item car1 item0) 0)
    (= (agent-carrying-item car1 item1) 0)
    (= (agent-carrying-item car1 item2) 0)
    (= (agent-carrying-item car1 item3) 0)
    (= (agent-carrying-item car1 item4) 0)
    (= (agent-carrying-item car1 item5) 0)
    (= (agent-carrying-item car1 item6) 0)
    (= (agent-carrying-item car1 item7) 0)
    (= (agent-carrying-item car1 item8) 0)
    (= (agent-carrying-item car1 item9) 0)
    (= (agent-carrying-item car1 item10) 0)
    (= (agent-carrying-item car2 item0) 0)
    (= (agent-carrying-item car2 item1) 0)
    (= (agent-carrying-item car2 item2) 0)
    (= (agent-carrying-item car2 item3) 0)
    (= (agent-carrying-item car2 item4) 0)
    (= (agent-carrying-item car2 item5) 0)
    (= (agent-carrying-item car2 item6) 0)
    (= (agent-carrying-item car2 item7) 0)
    (= (agent-carrying-item car2 item8) 0)
    (= (agent-carrying-item car2 item9) 0)
    (= (agent-carrying-item car2 item10) 0)
    (= (agent-carrying-item car3 item0) 0)
    (= (agent-carrying-item car3 item1) 0)
    (= (agent-carrying-item car3 item2) 0)
    (= (agent-carrying-item car3 item3) 0)
    (= (agent-carrying-item car3 item4) 0)
    (= (agent-carrying-item car3 item5) 0)
    (= (agent-carrying-item car3 item6) 0)
    (= (agent-carrying-item car3 item7) 0)
    (= (agent-carrying-item car3 item8) 0)
    (= (agent-carrying-item car3 item9) 0)
    (= (agent-carrying-item car3 item10) 0)
    (= (agent-carrying-item car4 item0) 0)
    (= (agent-carrying-item car4 item1) 0)
    (= (agent-carrying-item car4 item2) 0)
    (= (agent-carrying-item car4 item3) 0)
    (= (agent-carrying-item car4 item4) 0)
    (= (agent-carrying-item car4 item5) 0)
    (= (agent-carrying-item car4 item6) 0)
    (= (agent-carrying-item car4 item7) 0)
    (= (agent-carrying-item car4 item8) 0)
    (= (agent-carrying-item car4 item9) 0)
    (= (agent-carrying-item car4 item10) 0)

    (= (item-in-storage item0 storage0) 0)
    (= (item-in-storage item1 storage0) 0)
    (= (item-in-storage item2 storage0) 0)
    (= (item-in-storage item3 storage0) 0)
    (= (item-in-storage item4 storage0) 0)
    (= (item-in-storage item5 storage0) 0)
    (= (item-in-storage item6 storage0) 0)
    (= (item-in-storage item7 storage0) 0)
    (= (item-in-storage item8 storage0) 0)
    (= (item-in-storage item9 storage0) 0)
    (= (item-in-storage item10 storage0) 0)
    (= (item-in-storage item0 storage1) 0)
    (= (item-in-storage item1 storage1) 0)
    (= (item-in-storage item2 storage1) 0)
    (= (item-in-storage item3 storage1) 0)
    (= (item-in-storage item4 storage1) 0)
    (= (item-in-storage item5 storage1) 0)
    (= (item-in-storage item6 storage1) 0)
    (= (item-in-storage item7 storage1) 0)
    (= (item-in-storage item8 storage1) 0)
    (= (item-in-storage item9 storage1) 0)
    (= (item-in-storage item10 storage1) 0)
    (= (item-in-storage item0 storage2) 0)
    (= (item-in-storage item1 storage2) 0)
    (= (item-in-storage item2 storage2) 0)
    (= (item-in-storage item3 storage2) 0)
    (= (item-in-storage item4 storage2) 0)
    (= (item-in-storage item5 storage2) 0)
    (= (item-in-storage item6 storage2) 0)
    (= (item-in-storage item7 storage2) 0)
    (= (item-in-storage item8 storage2) 0)
    (= (item-in-storage item9 storage2) 0)
    (= (item-in-storage item10 storage2) 0)
    (= (item-in-storage item0 storage3) 0)
    (= (item-in-storage item1 storage3) 0)
    (= (item-in-storage item2 storage3) 0)
    (= (item-in-storage item3 storage3) 0)
    (= (item-in-storage item4 storage3) 0)
    (= (item-in-storage item5 storage3) 0)
    (= (item-in-storage item6 storage3) 0)
    (= (item-in-storage item7 storage3) 0)
    (= (item-in-storage item8 storage3) 0)
    (= (item-in-storage item9 storage3) 0)
    (= (item-in-storage item10 storage3) 0)
    (= (item-in-storage item0 storage0) 0)
    (= (item-in-storage item1 storage0) 0)
    (= (item-in-storage item2 storage0) 0)
    (= (item-in-storage item3 storage0) 0)
    (= (item-in-storage item4 storage0) 0)
    (= (item-in-storage item5 storage0) 0)
    (= (item-in-storage item6 storage0) 0)
    (= (item-in-storage item7 storage0) 0)
    (= (item-in-storage item8 storage0) 0)
    (= (item-in-storage item9 storage0) 0)
    (= (item-in-storage item10 storage0) 0)
    (= (item-in-storage item0 storage1) 0)
    (= (item-in-storage item1 storage1) 0)
    (= (item-in-storage item2 storage1) 0)
    (= (item-in-storage item3 storage1) 0)
    (= (item-in-storage item4 storage1) 0)
    (= (item-in-storage item5 storage1) 0)
    (= (item-in-storage item6 storage1) 0)
    (= (item-in-storage item7 storage1) 0)
    (= (item-in-storage item8 storage1) 0)
    (= (item-in-storage item9 storage1) 0)
    (= (item-in-storage item10 storage1) 0)
    (= (item-in-storage item0 storage2) 0)
    (= (item-in-storage item1 storage2) 0)
    (= (item-in-storage item2 storage2) 0)
    (= (item-in-storage item3 storage2) 0)
    (= (item-in-storage item4 storage2) 0)
    (= (item-in-storage item5 storage2) 0)
    (= (item-in-storage item6 storage2) 0)
    (= (item-in-storage item7 storage2) 0)
    (= (item-in-storage item8 storage2) 0)
    (= (item-in-storage item9 storage2) 0)
    (= (item-in-storage item10 storage2) 0)
    (= (item-in-storage item0 storage3) 0)
    (= (item-in-storage item1 storage3) 0)
    (= (item-in-storage item2 storage3) 0)
    (= (item-in-storage item3 storage3) 0)
    (= (item-in-storage item4 storage3) 0)
    (= (item-in-storage item5 storage3) 0)
    (= (item-in-storage item6 storage3) 0)
    (= (item-in-storage item7 storage3) 0)
    (= (item-in-storage item8 storage3) 0)
    (= (item-in-storage item9 storage3) 0)
    (= (item-in-storage item10 storage3) 0)
    (= (item-in-storage item0 storage4) 0)
    (= (item-in-storage item1 storage4) 0)
    (= (item-in-storage item2 storage4) 0)
    (= (item-in-storage item3 storage4) 0)
    (= (item-in-storage item4 storage4) 0)
    (= (item-in-storage item5 storage4) 0)
    (= (item-in-storage item6 storage4) 0)
    (= (item-in-storage item7 storage4) 0)
    (= (item-in-storage item8 storage4) 0)
    (= (item-in-storage item9 storage4) 0)
    (= (item-in-storage item10 storage4) 0)
)

(:goal (and
        (= (agent-carrying-item truck1 item9) 1)
    )
)

;un-comment the following line if metric is needed
;(:metric minimize (???))
)
